### ISSUE TITLE
Upload version of zlib and libpng (Windows)

### ISSUE THREAD

**Issue by mitkof6** [tgeijten/scone-studio#2]
Could you please upload on SimTK or share the version of zlib and libpng that you use to build OSG on Windows? Thanks!

**Comment by tgeijten** [comment]
Hi Dimitar,

This is were I build the binaries from:

https://github.com/bjornblissing/osg-3rdparty-cmake

Cheers,
Thomas


From: Dimitar Stanev ***@***.***>
Sent: Monday, June 7, 2021 9:33
To: tgeijten/scone-studio ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tgeijten/scone-studio] Upload version of zlib and libpng (Windows) (#2)


Could you please upload on SimTK or share the version of zlib and libpng that you use to build OSG on Windows? Thanks!

**Comment by mitkof6** [comment]
Thanks!
