### ISSUE TITLE
Creating video is unpredictable if the visualizer is currently playing a video

### ISSUE THREAD

**Issue by PashavanBijlert** [tgeijten/scone-studio#4]
**Describe the bug**
Creating video is unpredictable if the visualizer is currently playing a video

**To Reproduce**
1. Load in a .sto
2. play the motion on repeat
3. Press generate video while the motion is still playing
4. Resulting video is glitchy

**Expected behavior**
Non-glitchy video.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - SCONE Version 2.0.0.2164 BETA 11 and 2.0.0.2286

**Additional context**

**Comment by tgeijten** [comment]
Fixed, thanks!
