### ISSUE TITLE
Download requires personal email + manual account approval

### ISSUE THREAD

**Issue by josephrocca** [tgeijten/scone-studio#8]
Based on this page: https://scone.software/doku.php?id=install It seems that an account with SimTk.org is required to download pre-built packages of this software? If my understanding is correct, can you please make the Linux `.deb` available at a public URL for those of us who aren't at a university?

**Comment by tgeijten** [comment]
You do need SimTk account, but you don't need to be at a university to create one. I have never heard about any issues creating an account without a university affiliation.

**Comment by josephrocca** [comment]
@tgeijten That's good to know, so I the account I made will be approved eventually.

But still - it's quite unusual to require someone's personal email in order to download open source software - and then to also make them sit and wait until someone manually approves their account. Can you please add a public link somewhere? E.g. using Github Releases, or something like that?

**Comment by tgeijten** [comment]
For biomechanics researchers (the target audience) it's quite really common to download software via SimTK.

Alternatively, you can download packages from the GitHub Actions page, but these don't include support for the (proprietary) [Hyfydy simulation engine](https://hyfydy.com).

**Comment by josephrocca** [comment]
Ah thank you! I didn't think to check the Github Actions page. Okay time to have some fun!

(I am basically a hobbyist, as you can probably tell - I saw [your video](https://www.youtube.com/watch?v=pgaEE27nsQw) about 7 years ago and did an undergrad project on 'virtual creatures' inspired by it, then got distracted by web development and life/career for several years, and am now back to dabbling in this area, and have just stumbled back into your work via [this project](https://github.com/martius-lab/depRL). Thank you for all your incredible contributions to science and open source! :pray:)
